-- Extra autostart processes for the phone session.
--
-- Empty on purpose, and worth writing down rather than leaving to be rediscovered.
-- upstream's default/hypr/autostart.lua already starts the shell with
-- omarchy-launch-shell, which runs `quickshell -n -p "$OMARCHY_PATH/shell"`.
-- Until shell/ in this repo has a root for that to point at, the phone session
-- inherits the desktop shell: a desktop bar squeezed onto 360 logical px. Ugly,
-- but real, and it lets the session underneath be exercised on hardware now.
--
-- When shell/ lands, the phone shell gets launched from here against this repo's
-- tree instead of $OMARCHY_PATH's, and the desktop one is suppressed. That
-- single line is what this file is waiting for.
