-- Extra autostart processes for the phone session.
--
-- Empty on purpose. Upstream's default/hypr/autostart.lua already starts the
-- shell with omarchy-launch-shell, and that is the right shell: the phone's
-- surface is not a separate Quickshell config but a set of plugins inside
-- upstream's host (README.md, NOTES.md), selected by shell.json -- bar.id for
-- the phone bar, plugins[] for the home screen and keyboard. The installer
-- writes both. Nothing here needs starting that upstream does not start.
